### ISSUE TITLE
bridgy init got erro: sample yaml file not found

### ISSUE THREAD

**Issue by gwanii** [wagoodman/bridgy#21]
'''
Traceback (most recent call last):
  File "/home/hhhhh/.local/bin/bridgy", line 11, in <module>
    sys.exit(main())
  File "/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/__main__.py", line 340, in main
    init_handler(args, config)
  File "/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/utils.py", line 32, in wrapper
    func(*args,**kwargs)
  File "/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/__main__.py", line 312, in init_handler
    if config.create():
  File "/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/config/base.py", line 89, in create
    fh.write(self.config_template_contents)
  File "/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/config/base.py", line 64, in config_template_contents
    return pkgutil.get_data('bridgy', 'config/samples/' + self.config_template_path)
  File "/usr/lib/python3.6/pkgutil.py", line 634, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/hhhhh/.local/lib/python3.6/site-packages/bridgy/config/samples/sample_config_2.yml'
'''

**Comment by wagoodman** [comment]
Looks like I didn't include a Manifest.in with the data files. Fixed in c5d82e76467b56f36d193f8226412fd27f59fc90 (v0.1.9)
