### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by pascaldevink** [wagoodman/bridgy#23]
I've just installed bridgy on a new machine (having it working on another), and with the exact same configuration file, I've hit this error upon updating: `botocore.exceptions.NoRegionError: You must specify a region.`. However, I do specify the region in the config file.

The full output of the `bridgy update -v` command:
```
Updating inventory...
Loading variable profile from defaults.
Loading variable config_file from defaults.
Loading variable credentials_file from defaults.
Loading variable data_path from defaults.
Loading variable profile from defaults.
Loading variable region from defaults.
attaching to session: Session(region_name=None)
datapath: /Users/pascaldevink/.bridgy/inventory/aws/production
Loading variable profile from defaults.
Loading variable region from defaults.
Loading variable profile from defaults.
Loading variable ca_bundle from defaults.
Loading variable profile from defaults.
Loading variable api_versions from defaults.
Loading variable profile from defaults.
Loading variable credentials_file from defaults.
Loading variable config_file from defaults.
Loading variable profile from defaults.
Loading variable metadata_service_timeout from defaults.
Loading variable profile from defaults.
Loading variable metadata_service_num_attempts from defaults.
Loading variable profile from defaults.
Looking for credentials via: env
Looking for credentials via: assume-role
Looking for credentials via: shared-credentials-file
Found credentials in shared credentials file: ~/.aws/credentials
Loading JSON file: /Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/data/endpoints.json
Loading variable profile from defaults.
Event choose-service-name: calling handler <function handle_service_name_alias at 0x10cf509d8>
Loading JSON file: /Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/data/ec2/2016-11-15/service-2.json
Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x10cf2a488>
Event creating-client-class.ec2: calling handler <bound method Pill._create_client of <placebo.pill.Pill object at 0x10d3c1d68>>
_create_client
Traceback (most recent call last):
  File "/Users/pascaldevink/.local/bin/bridgy", line 11, in <module>
    sys.exit(main())
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/__main__.py", line 373, in main
    handler(args, config)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/utils.py", line 32, in wrapper
    func(*args,**kwargs)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/__main__.py", line 274, in update_handler
    inventory_obj = inventory.inventory(config)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/utils.py", line 49, in __call__
    return self[args]
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/utils.py", line 51, in __missing__
    ret = self[key] = self.f(*key)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/inventory/__init__.py", line 43, in inventory
    inv = AwsInventory(cache_dir, **srcCfg)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/bridgy/inventory/aws.py", line 41, in __init__
    self.client = session.client('ec2')
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 288, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 361, in resolve
    service_name, region_name)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/pascaldevink/Library/Python/3.6/lib/python/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

The relevant part of the config file:
```
config-schema: 2
inventory:
  update_at_start: true
  fuzzy_search: true
  source:
    - type: aws
      name: production
      region: eu-west-1
```
and of course I have a `~/.aws/credentials` file with the correct access key and secret.

Any clue what might cause this? Could it be a version thing of a dependency maybe?

**Comment by wagoodman** [comment]
I believe I see the issue... the configuration you've provided has only part of the information needed. That is, I'd expect one of the following for AWS configuration:
```yaml
  source:
    # reference a boto profile
    - type: aws
      name: Offsite
      profile: a-boto-profile-name
      region: eu-west-1

    # reference the ~/.aws/* configs
    - type: aws
      name: Offsite

    # manually set *all* variables here
    - type: aws
      name: Offsite
      access_key_id: AdfhjskfhdkfjfhskfTQ(fake)
      secret_access_key: ZdhfjkshfkjdhfjshfkhfjsE5xx/dhfjksdhfksjf(fake)
      session_token: someawesometoken(fake)
      region: us-west-2
```
Without **all** of the manual variables set a default session is used instead (so the region in your bridgy config is ignored.). The default sessions checks for particular config sources in order: https://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials

It seems that it's using the ~/.aws/* configs as you are suggesting, however, I'd bet that your ~/.aws/config (not credendials) doesn't have region set, for example:
```
$ cat ~/.aws/config
[default]
region = us-west-2
```

Try either adding a region to your ~/.aws/config or adding your credentials to the bridgy config instead. Either way, I should probably add a bit more validation to ensure that partial configurations throw better errors (or at least a warning before it dies with a weird error).

**Comment by wagoodman** [comment]
@pascaldevink did this solve your problem?

**Comment by pascaldevink** [comment]
@wagoodman Thanks, that fixed it indeed!

**Comment by ranadeepbasani** [comment]
By initializing the  os.environ['AWS_DEFAULT_REGION'] = 'us-east-1' below the imports fixed my issue
